### ISSUE TITLE
How to get the LPBA40_N4_RN dataset for the example

### ISSUE THREAD

**Issue by mgcyung** [microsoft/VoxHRNet#2]
Thanks for your great work. I'm trying to run the example but stuck by the dataset. It seems there are multiple LPBA40 datasets on the give site [ LPBA40](https://resource.loni.usc.edu/resources/atlases-downloads/), and the data file format are not nii as in the example. Is there a downloadable LPBA40_N4_RN dataset or could you give some details on how to generate the dataset in the example?

**Comment by DanielLeee** [comment]
Thanks for your interest. The dataset I adopted is the one named **_LPBA40 Subjects Delineation Space: MRI and label files in delineation space_** on the site [LPBA40](https://resource.loni.usc.edu/resources/atlases-downloads/).

For convenience, I have uploaded the preprocessed data in the release page, downloadable from [here](https://github.com/microsoft/VoxHRNet/releases/download/dataset/LPBA40_N4.zip). The uploaded data results from downloading the original dataset, format converting, renaming and performing N4 bias correction from the ANTs tool. Note that you have to split and rename the data files for later use by yourself.

**Comment by mgcyung** [comment]
Thanks for your reply and the details of the dataset and preprocessing. I will try with the preprocessed data first.
